# Используем фиксированную версию Flutter 3.35.6
FROM ghcr.io/cirruslabs/flutter:3.35.6 AS build-env

# Копирование кода
WORKDIR /app
COPY ozon_sales_dashboard/ .

RUN flutter pub get

# Сборка с base-href и API_BASE_URL
RUN flutter build web --release --base-href /dashboard/ --dart-define=API_BASE_URL=/api

# ЭТАП 2: Nginx
FROM nginx:alpine

# Копируем конфиг
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Копируем Flutter Web
COPY --from=build-env /app/build/web /usr/share/nginx/html/dashboard

# Копируем Лендинг
COPY landing/ /usr/share/nginx/html/landing

# Статика будет монтироваться через volume, но создадим директорию
RUN mkdir -p /usr/share/nginx/html/static

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
