"""add quantity to ozon_accruals

Revision ID: 2240ba87c4bf
Revises: 3f26258cd8eb
Create Date: 2026-07-01 16:06:44.516783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2240ba87c4bf'
down_revision: Union[str, None] = '3f26258cd8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ozon_accruals', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ozon_accruals', 'quantity')
    # ### end Alembic commands ###
