"""добавление таблицы себестоимости

Revision ID: 3f26258cd8eb
Revises: 9c93990e9532
Create Date: 2026-07-01 14:05:16.915005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f26258cd8eb'
down_revision: Union[str, None] = '9c93990e9532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.BigInteger(), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_costs_effective_from'), 'product_costs', ['effective_from'], unique=False)
    op.create_index(op.f('ix_product_costs_offer_id'), 'product_costs', ['offer_id'], unique=False)
    op.create_index(op.f('ix_product_costs_sku'), 'product_costs', ['sku'], unique=False)
    op.create_index(op.f('ix_product_costs_user_id'), 'product_costs', ['user_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_ozon_credentials_id'), 'ozon_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_ozon_credentials_id'), table_name='ozon_credentials')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_product_costs_user_id'), table_name='product_costs')
    op.drop_index(op.f('ix_product_costs_sku'), table_name='product_costs')
    op.drop_index(op.f('ix_product_costs_offer_id'), table_name='product_costs')
    op.drop_index(op.f('ix_product_costs_effective_from'), table_name='product_costs')
    op.drop_table('product_costs')
    # ### end Alembic commands ###
