"""add last_sync_attempt_at to sync_status

Revision ID: 4f6a8e2b1c3d
Revises: e7b3990e9533
Create Date: 2026-07-17 15:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6a8e2b1c3d'
down_revision: Union[str, None] = 'e7b3990e9533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_status', sa.Column('last_sync_attempt_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_status', 'last_sync_attempt_at')
    # ### end Alembic commands ###
