"""Initial baseline

Revision ID: 9c93990e9532
Revises: None
Create Date: 2026-06-23 14:25:07.543883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c93990e9532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_costs_date', table_name='costs')
    op.drop_index('idx_order_postings_created_at', table_name='order_postings')
    op.drop_index('idx_order_postings_in_process_at', table_name='order_postings')
    op.create_index(op.f('ix_order_postings_created_at'), 'order_postings', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_postings_in_process_at'), 'order_postings', ['in_process_at'], unique=False)
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_updated_at'), 'orders', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_updated_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_index(op.f('ix_order_postings_in_process_at'), table_name='order_postings')
    op.drop_index(op.f('ix_order_postings_created_at'), table_name='order_postings')
    op.create_index('idx_order_postings_in_process_at', 'order_postings', ['in_process_at'], unique=False)
    op.create_index('idx_order_postings_created_at', 'order_postings', ['created_at'], unique=False)
    op.create_index('idx_costs_date', 'costs', ['date'], unique=False)
    # ### end Alembic commands ###
